version: "3"

services:
  api-database:
    image: "bitnami/postgresql"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=heatdb
    volumes:
      - "pgdata:/bitnami/postgresql"
    networks:
      - api-network

  app-liboftech:
    build: .
    container_name: api-liboftech
    depends_on:
      - api-database
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  pgdata:
    driver: local